### ISSUE TITLE
Website framework

### ISSUE THREAD

**Issue by FunctionalMetatable** [scratch-contributors/scratch-contributors.github.io#1]
We could use html or jekyll/nuxt. jekyll and nuxt would make it possible for the bios to be rendered server-side unlike the TFH website.

What do you think @leahcimto?

**Comment by leahcimto** [comment]
I would be fine with jekyll and nuxt.

**Comment by gosoccerboy5** [comment]
I would vote HTML because that's the nitty gritty cool stuff but obviously nuxt + jekyll + vue makes the website easier and better (as evidenced by my website vs yours). Honestly whatever you think is best
