### ISSUE TITLE
possible rewrite in html

### ISSUE THREAD

**Issue by FunctionalMetatable** [scratch-contributors/scratch-contributors.github.io#15]
The site maybe complex for potential contributors to write code.
cc @leahcimto @gosoccerboy5

**Comment by gosoccerboy5** [comment]
I like html, so I'd be fine with that. but vue or whatever you're using seems to work really well too, so I would stick with that

**Comment by jeffalo** [comment]
with something like this where you're going to be rendering lists, basic html might be even harder to understand than Vue. just add a short paragraph into the readme about the project structure and it'll be clear.
