### ISSUE TITLE
Whats this about

### ISSUE THREAD

**Issue by gosoccerboy5** [scratch-contributors/scratch-contributors.github.io#2]
I saw a comment by 9gr on leahcimto's profile so I logically went here. now I know 9gr and leahcimto are probably members. whats going on here? i wanna get in on the action 😎

**Comment by FunctionalMetatable** [comment]
https://scratch.mit.edu/studios/26371714/ <= Scratch Contributors
This is the site for the studio. I'm currently working on the site in my own branch. If you want I can invite you to the org?

**Comment by gosoccerboy5** [comment]
Ok. Could you invite me? I will leave if I find nothing of interest
